{
 "title": "Bank App - Бизнес метрики",
 "tags": [
  "bank-app",
  "business"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Количество пополнений",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bank_cash_deposit_seconds_count)",
     "legendFormat": "пополнения"
    }
   ]
  },
  {
   "title": "Количество снятий со счета",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bank_cash_withdraw_seconds_count)",
     "legendFormat": "снятия"
    }
   ]
  },
  {
   "title": "Количество переводов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bank_transfer_seconds_count)",
     "legendFormat": "переводы"
    }
   ]
  },
  {
   "title": "Количество неудачных переводов",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bank_transfer_failed_total)",
     "legendFormat": "неудачные"
    }
   ]
  },
  {
   "title": "Обработано переводов",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bank_transfer_seconds_count) - sum(bank_transfer_failed_total)",
     "legendFormat": "Успешно"
    },
    {
     "expr": "sum(bank_transfer_failed_total{exception=\"InsufficientBalanceException\"})",
     "legendFormat": "InsufficientBalanceException"
    },
    {
     "expr": "sum(bank_transfer_failed_total{exception=\"AccountNotFoundException\"})",
     "legendFormat": "AccountNotFoundException"
    },
    {
     "expr": "sum(bank_transfer_failed_total{exception=\"RuntimeException\"})",
     "legendFormat": "RuntimeException"
    }
   ]
  },
  {
   "title": "Среднее время обработки уведомлений",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(bank_notifications_process_seconds_sum[5m]) / rate(bank_notifications_process_seconds_count[5m])",
     "legendFormat": "среднее"
    }
   ]
  },
  {
   "title": "Среднее время обработки операций перевода",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(bank_transfer_seconds_sum[5m]) / rate(bank_transfer_seconds_count[5m])",
     "legendFormat": "среднее"
    }
   ]
  },
  {
   "title": "Среднее время обработки операций снятия/пополнения",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(bank_cash_withdraw_seconds_sum[5m]) / rate(bank_cash_withdraw_seconds_count[5m])",
     "legendFormat": "снятие"
    },
    {
     "expr": "rate(bank_cash_deposit_seconds_sum[5m]) / rate(bank_cash_deposit_seconds_count[5m])",
     "legendFormat": "пополнение"
    }
   ]
  }
 ]
}