replicaCount: 1
image:
  repository: bank-gateway
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: bank-gateway
  port: 80
  targetPort: 8081
config:
  data:
    SERVER_PORT: "8081"
    KEYCLOAK_HOST: keycloak
    KEYCLOAK_PORT: "80"
    KEYCLOAK_REALM: bank
    FRONT_UI_ORIGIN: "http://localhost"
