replicaCount: 1
image:
  repository: bank-cash
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: bank-cash
  port: 80
  targetPort: 8083
config:
  data:
    SERVER_PORT: "8083"
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_NAME: bank
    DB_USERNAME: postgres
    SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/bank?currentSchema=cash"
    KEYCLOAK_HOST: keycloak
    KEYCLOAK_PORT: "80"
    KEYCLOAK_REALM: bank
    ACCOUNTS_BASE_URL: "http://bank-accounts"
    KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
secret:
  data:
    DB_PASSWORD: postgres
    KEYCLOAK_CLIENT_SECRET: cash-secret
