spring:
  config:
    import: "consul:"
  application:
    name: bank-front-ui
  session:
    store-type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${server.port}
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bank-front-ui
            client-secret: ${KEYCLOAK_CLIENT_SECRET:}
            client-authentication-method: none
            authorization-grant-type: authorization_code
            scope: openid, profile, accounts:read, accounts:write, cash:operate, transfer:execute
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8089}/realms/${KEYCLOAK_REALM:bank}
            user-name-attribute: preferred_username

gateway:
  service-id: bank-gateway

server:
  port: ${SERVER_PORT:8080}
