apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-secret
  labels:
    app: {{ .Release.Name }}-postgres
type: Opaque
data:
  password: {{ .Values.secrets.password | b64enc | quote }}
