spring:
  application:
    name: bank-accounts
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bank}?currentSchema=accounts
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    contexts: ${IMPORT_DEMO_DATA:false}
  lifecycle:
    timeout-per-shutdown-phase: 30s
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8089}/realms/${KEYCLOAK_REALM:bank}/protocol/openid-connect/certs
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  topic:
    notifications:
      name: ${KAFKA_TOPIC_NOTIFICATIONS:notifications}

server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
