spring:
  config:
    import: "consul:"
  application:
    name: bank-gateway
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:market}?currentSchema=gateway
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8089}/realms/${KEYCLOAK_REALM:bank}
server:
  port: ${SERVER_PORT:8081}
