spring:
  application:
    name: bank-gateway
  lifecycle:
    timeout-per-shutdown-phase: 30s
  reactor:
    context-propagation: auto
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "${FRONT_UI_ORIGIN:http://bank-front-ui:8080}"
            allowedMethods: "GET,POST,PUT,DELETE"
            allowedHeaders: "*"
      httpclient:
        connect-timeout: 2000
        response-timeout: 10s
        observation:
          enabled: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_HOST:keycloak}:${KEYCLOAK_PORT:8089}/realms/${KEYCLOAK_REALM:bank}/protocol/openid-connect/certs

gateway:
  routes:
    accounts-url: ${ACCOUNTS_SERVICE_URL:http://bank-accounts}
    cash-url: ${CASH_SERVICE_URL:http://bank-cash}
    transfer-url: ${TRANSFER_SERVICE_URL:http://bank-transfer}

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 60s
    instances:
      accountsCircuitBreaker:
        base-config: default
      cashCircuitBreaker:
        base-config: default
      transferCircuitBreaker:
        base-config: default
      notificationsCircuitBreaker:
        base-config: default
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
    instances:
      accountsCircuitBreaker:
        base-config: default
      cashCircuitBreaker:
        base-config: default
      transferCircuitBreaker:
        base-config: default
      notificationsCircuitBreaker:
        base-config: default

management:
  endpoint:
    gateway:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,gateway,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}

server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful

