apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.name }}-config
  labels:
    app: {{ .Values.service.name }}
data:
  realm-export.json: |
{{ .Files.Get "realm-export.json" | nindent 4 }}
