apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.service.name }}-secret
  labels:
    app: {{ .Values.service.name }}
type: Opaque
data:
  admin-password: {{ .Values.secrets.adminPassword | b64enc | quote }}
  db-password: {{ .Values.secrets.dbPassword | b64enc | quote }}
