input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    gsub => [
      "message", "(?i)(password|client[_-]?secret|secret)\s*[=:]\s*[^\s,;}\"]+", "\1=******"
    ]
  }
  if [traceId] {
    mutate { add_field => { "[trace][id]" => "%{traceId}" } }
  }
  if [spanId] {
    mutate { add_field => { "[span][id]" => "%{spanId}" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bank-logs-%{+YYYY.MM.dd}"
  }
}
