apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.logstash.service.name }}
  labels:
    app: {{ .Values.logstash.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.logstash.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.logstash.service.name }}
      
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/logstash-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: logstash
          image: "{{ .Values.logstash.image.repository }}:{{ .Values.logstash.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.logstash.service.tcpPort }}
              name: tcp-json
            - containerPort: {{ .Values.logstash.service.apiPort }}
              name: api
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.logstash.service.apiPort }}
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 30
          volumeMounts:
            - name: config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: config
              mountPath: /usr/share/logstash/pipeline/pipeline.conf
              subPath: pipeline.conf
      volumes:
        - name: config
          configMap:
            name: {{ .Values.logstash.service.name }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.logstash.service.name }}
  labels:
    app: {{ .Values.logstash.service.name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.logstash.service.tcpPort }}
      targetPort: {{ .Values.logstash.service.tcpPort }}
      protocol: TCP
      name: tcp-json
    - port: {{ .Values.logstash.service.apiPort }}
      targetPort: {{ .Values.logstash.service.apiPort }}
      protocol: TCP
      name: api
  selector:
    app: {{ .Values.logstash.service.name }}
