{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bank-app.fullname" . }}
  labels:
    {{- include "bank-app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ index .Values "bank-front-ui" "service" "name" }}
                port:
                  number: {{ index .Values "bank-front-ui" "service" "port" }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.keycloak.service.name }}
                port:
                  number: {{ .Values.keycloak.service.port }}
{{- end }}
