input {
  tcp {
    port => {{ .Values.logstash.service.tcpPort }}
    codec => json_lines
  }
}

filter {
  mutate {
    gsub => [
      # +-стандартный фильтр, но не думаю что подобное есть где-то на сервисах
      "message", "(?i)(password|client[_-]?secret|secret)\s*[=:]\s*[^\s,;}\"]+", "\1=******"
    ]
  }
  if [traceId] {
    mutate { add_field => { "[trace][id]" => "%{traceId}" } }
  }
  if [spanId] {
    mutate { add_field => { "[span][id]" => "%{spanId}" } }
  }
}

output {
  elasticsearch {
    hosts => ["http://{{ .Values.elasticsearch.service.name }}:{{ .Values.elasticsearch.service.port }}"]
    index => "{{ .Values.logstash.index }}-%{+YYYY.MM.dd}"
  }
}
