apiVersion: v2
name: bank-front-ui
description: Веб-интерфейс банковского приложения
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: microservice-lib
    version: 0.1.0
    repository: file://../microservice-lib
